title: DediStatus
buildFuture: true
defaultContentLanguage: en
languageCode: en
baseURL: https://gregarious-chimera-319e33.netlify.app/
theme: cstate
preserveTaxonomyNames: true
taxonomies:
  affected: affected
outputs:
  page:
    - html
    - json
  section:
    - html
    - json
    - rss
  home:
    - html
    - json
    - rss
    - svg
  term:
    - html
    - json
    - rss
    - svg
outputFormats:
  svg:
    isPlainText: true
    mediaType: image/svg+xml
enableGitInfo: true
params:
  skipSeconds: false
  useRelativeTime: true
  disableDarkMode: false
  shortDateFormat: 15:04 UTC — Jan 2
  down: "#e60000"
  systems: []
  dateFormat: January 2, 2006 at 3:04 PM UTC
  brand: "#0018a7"
  enableLastMod: true
  headerTextColor: white
  logo: https://dedipath.com/assets/images/logo.png
  incidentPostsPerPage: 10
  googleAnalytics: UA-00000000-1
  alwaysKeepBrandColor: true
  disableComplexCalculations: false
  useLogo: true
  disrupted: "#cc4400"
  notice: "#24478f"
  incidentHistoryFormat: yearly
  disableIncidentHistory: false
  ok: "#008000"
  categories:
    - name: Portals
      closed: true
    - closed: false
      name: ATL
      description: 12655 Edison Drive, Alpharetta, GA 30005
    - description: "1950 N Stemmons Fwy #2033, Dallas, TX 75207"
      name: DAL
      closed: false
    - name: DEN
      description: 8636 S Peoria St, Englewood, CO 80112
      closed: false
    - name: JAX
      description: 4905 Belfort Rd, Unit 145, Jacksonville, Florida 32256
      closed: false
    - name: LAS
      description: 3330 E Lone Mountain Rd, North Las Vegas, NV 89081
      closed: false
    - name: LAX
      description: 3690 Redondo Beach Avenue, Los Angeles 90278
      closed: false
    - name: NYJ
      description: 1 Enterprise Avenue North, Secaucus, NJ 07094
      closed: false
    - name: PHX
      description: 2500 W Frye Road, Chandler, AZ 85224
      closed: false
    - name: SEF
      description: 3355 S 120th Place, Tukwila, WA 98168
      closed: false
    - name: SJE
      description: 2151 Mission College Blvd, Santa Clara, CA 95054
      closed: false
  description: We continuously monitor the status of our services and if there are
    any interruptions, a note will be posted here.
  enableCustomHTML: true
  useLargeHeaderDesign: false
